language: node_js
node_js:
  - "node"

before_script:
  - npm install -g gulp-cli

install:
  - npm i

script:
  - npm run build

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  keep-history: false
  local-dir: dist
  on:
    branch: development